version: '3.8'

volumes:
  app:
  db:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - app:/app
    working_dir: /app
    command: /bin/sh
    tty: true
  server:
    build:
      context: ../src
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /app/src/
    volumes:
      - app:/app
    ports:
      - 30001:3000
    command: yarn dev:app
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
